// Code generated by hertz generator.

package user

import (
	middleware "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/middelware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _userinfoupdateMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}
