// Code generated by hertz generator.

package user

import (
	middleware "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/middelware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _userMw() []app.HandlerFunc { return nil }

func _userloginMw() []app.HandlerFunc {
	return nil
}

func _userregisterMw() []app.HandlerFunc {
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _userinfoupdateMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _teacherMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _createcourseMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _deletecourseMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _invitestudentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _updateMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _courseMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _updatecourseMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _operatememberMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _selectmycoursesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadvideosMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _studentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _studentmycoursesMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _deletevideoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _queryMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _enquirystudentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _teacher0Mw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _enquirymycoursesMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _uidinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
