import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/themes/default.css";
import "@/styles/globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import {ScreenRecordProvider} from "@/context/screen-record-provider";
import {NotificationProvider} from "@/context/notification-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <ThemeProvider>
            <NotificationProvider>
                <ScreenRecordProvider>
                    
                    {children}
                </ScreenRecordProvider>
            </NotificationProvider>

        </ThemeProvider>
      </body>
    </html>
  );
}
