// Code generated by hertz generator.

package main

import (
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/dal/pg"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/dal/redis"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/utils"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	pg.InitDB()
	redis.InitRedis()
	utils.LogoPrint()

	h := server.Default()

	register(h)
	h.Spin()
}
