// Code generated by hertz generator.

package video

import (
	middleware "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/middelware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _videoinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
