// Code generated by hertz generator.

package admin

import (
	"context"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/dal/pg/entity"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/model/base"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/model/srverror"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/service"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/utils"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"net/http"
	"strconv"

	admin "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/model/admin"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// DeleteTarget .
// @router /admin/delete [POST]
func DeleteTarget(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DeleteTargetReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.DeleteTargetResp)
	resp.Base = new(base.BaseResponse)
	_, authority, err := utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if authority != entity.AuthoritySuperAdmin {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = "用户权限不够"
		c.JSON(consts.StatusOK, resp)
		return
	}
	tid, err := strconv.ParseInt(req.Tid, 10, 64)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		hlog.Error("对象id数据格式转换失败：", err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	if req.Target == "video" {
		err = service.VideoServ().DeleteVideoWithVid(ctx, tid)
	} else if req.Target == "user" {
		err = service.UserServ().DeleteUserWithUid(ctx, tid)
	} else if req.Target == "course" {
		err = service.CourseServ().DeleteCourseWithCid(ctx, tid)
	}
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Base = srverror.WrapWithSuccess("删除对象成功")
	c.JSON(consts.StatusOK, resp)
}

// UpdateUserInfo .
// @router /admin/update/user [POST]
func UpdateUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.UpdateUserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.UpdateUserInfoResp)
	resp.Base = new(base.BaseResponse)
	_, authority, err := utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if authority != entity.AuthoritySuperAdmin {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = "用户权限不够"
		c.JSON(consts.StatusOK, resp)
		return
	}
	uid, err := strconv.ParseInt(req.UID, 10, 64)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		hlog.Error("用户id数据格式转换失败：", err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	err = service.UserServ().UpdateUserInfoWithId(ctx, uid, req.Name, req.Avatar, req.Phone, req.Signature)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	err = service.UserServ().UpdateUserIdentityWithUid(ctx, uid, req.Authority)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Base = srverror.WrapWithSuccess("更新用户信息成功")
	c.JSON(consts.StatusOK, resp)
}

// UploadVideo .
// @router /admin/uploadvideo [POST]
func UploadVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.UploadVideoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.UploadVideoResp)
	resp.Base = new(base.BaseResponse)
	uid, authority, err := utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if authority != entity.AuthoritySuperAdmin {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = "用户权限不够"
		c.JSON(consts.StatusOK, resp)
		return
	}
	cid, err := strconv.ParseInt(req.Cid, 10, 64)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		hlog.Error("课程域id数据格式转换失败：", err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	timestr, err := utils.GetNowTime()
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		hlog.Error("加载位置出错：", err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	newid, err := service.VideoServ().UploadVideoWithCidAndUid(ctx, uid, cid, req.Title, req.Description, req.Cover, req.Length, timestr, req.Chapter)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Base = srverror.WrapWithSuccess("上传视频成功")
	resp.Newid = strconv.FormatInt(newid, 10)
	c.JSON(consts.StatusOK, resp)
}

// CreateCourse .
// @router /admin/createcourse [POST]
func CreateCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.CreateCourseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.CreateCourseResp)
	resp.Base = new(base.BaseResponse)
	uid, authority, err := utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if authority != entity.AuthoritySuperAdmin {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = "用户权限不够"
		c.JSON(consts.StatusOK, resp)
		return
	}
	err = service.CourseServ().CreateCourseWithUid(ctx, uid, req.Title, req.Description, req.Cover, req.BeginTime, req.EndTime, req.Major, req.Faculty, req.Class)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Base = srverror.WrapWithSuccess("创建课程域成功")
	c.JSON(consts.StatusOK, resp)
}

// DeleteUserFromCourse .
// @router /admin/update/course/member [POST]
func DeleteUserFromCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DeleteUserFromCourseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.DeleteUserFromCourseResp)
	resp.Base = new(base.BaseResponse)
	_, authority, err := utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if authority != entity.AuthoritySuperAdmin {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = "用户权限不够"
		c.JSON(consts.StatusOK, resp)
		return
	}
	cid, err := strconv.ParseInt(req.Cid, 10, 64)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		hlog.Error("课程域id数据格式转换失败：", err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	uid, err := strconv.ParseInt(req.UID, 10, 64)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		hlog.Error("用户id数据格式转换失败：", err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	err = service.CourseServ().OperateMemberWithCidAndUid(ctx, cid, uid)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Base = srverror.WrapWithSuccess("删除课程域成员成功")
	c.JSON(consts.StatusOK, resp)
}

// UpdateCourseInfo .
// @router /admin/update/course [POST]
func UpdateCourseInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.UpdateCourseInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.UpdateCourseInfoResp)
	resp.Base = new(base.BaseResponse)
	_, authority, err := utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if authority != entity.AuthoritySuperAdmin {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = "用户权限不够"
		c.JSON(consts.StatusOK, resp)
		return
	}
	cid, err := strconv.ParseInt(req.Cid, 10, 64)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		hlog.Error("课程域id数据格式转换失败：", err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	err = service.CourseServ().UpdateCourseWithCid(ctx, cid, req.Title, req.Description, req.Cover, req.BeginTime, req.EndTime, req.Ascription, req.Faculty, req.Major)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Base = srverror.WrapWithSuccess("更新课程域信息成功")
	c.JSON(consts.StatusOK, resp)
}

// ImportStudents .
// @router /admin/import [POST]
func ImportStudents(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.ImportStudentsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.ImportStudentsResp)
	resp.Base = new(base.BaseResponse)
	_, authority, err := utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if authority != entity.AuthoritySuperAdmin {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = "用户权限不够"
		c.JSON(consts.StatusOK, resp)
		return
	}
	for _, student := range req.Students {
		err = service.UserServ().UserRegister(ctx, student.Name, student.Phone, "123456")
		if err != nil {
			resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
			c.JSON(consts.StatusOK, resp)
			return
		}
	}
	resp.Base = srverror.WrapWithSuccess("学生数据导入成功")
	c.JSON(consts.StatusOK, resp)
}

// EnquirytCourse .
// @router /admin/query/course [POST]
func EnquirytCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.EnquiryCourseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.EnquiryCourseResp)

	resp.Base = new(base.BaseResponse)
	_, authority, err := utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if authority != entity.AuthoritySuperAdmin {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = "用户权限不够"
		c.JSON(consts.StatusOK, resp)
		return
	}
	result, err := service.CourseServ().AdminQueryCourse(ctx, req.Keyword, req.Size, req.Offset, req.Major, req.Faculty, req.BeginTime, req.EndTime)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Courses = result
	resp.Base = srverror.WrapWithSuccess("查询课程域成功")
	c.JSON(consts.StatusOK, resp)
}

// EnquiryVideo .
// @router /admin/query/video [POST]
func EnquiryVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.EnquiryVideoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.EnquiryVideoResp)

	resp.Base = new(base.BaseResponse)
	_, authority, err := utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if authority != entity.AuthoritySuperAdmin {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = "用户权限不够"
		c.JSON(consts.StatusOK, resp)
		return
	}
	result, err := service.VideoServ().AdminQueryVideo(ctx, req.Keyword, req.Size, req.Offset, req.Major)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Videos = result
	resp.Base = srverror.WrapWithSuccess("查询视频成功")
	c.JSON(consts.StatusOK, resp)
}

// EnquiryUser .
// @router /admin/query/user [POST]
func EnquiryUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.EnquiryUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.EnquiryUserResp)

	resp.Base = new(base.BaseResponse)
	_, authority, err := utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if authority != entity.AuthoritySuperAdmin {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = "用户权限不够"
		c.JSON(consts.StatusOK, resp)
		return
	}
	result, err := service.UserServ().AdminQueryUser(ctx, req.Keyword, req.Size, req.Offset, req.Major, req.Faculty, req.Authority)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Users = result
	resp.Base = srverror.WrapWithSuccess("查询用户成功")
	c.JSON(consts.StatusOK, resp)
}
