// Code generated by hertz generator.

package notification

import (
	middleware "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/middelware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _notificationMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _querynotificationMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _notificationundercourseMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _createnotificationMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _browsenotificationMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}
