services:
  app:
    image: beriholic/kns:0.1.0
    ports:
      - "8888:8888"
    volumes:
      - ./config:/app/config
  database:
    image: postgres:latest
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: KS
    volumes:
      - ks_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    # ports:
    #   - "6379:6379"
    volumes:
      - ks_redis_data:/data

volumes:
  ks_pg_data:
  ks_redis_data:
