// Code generated by hertz generator.

package video

import (
	"context"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/model/base"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/model/srverror"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/service"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/utils"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"net/http"
	"strconv"

	video "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/model/video"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// VideoInfo .
// @router /video/info [POST]
func VideoInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoInfoResp)
	resp.Base = new(base.BaseResponse)
	_, _, err = utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(http.StatusUnauthorized, resp)
		return
	}
	vid, err := strconv.ParseInt(req.Vid, 10, 64)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		hlog.Error("视频id数据格式转换失败：", err)
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	result, err := service.VideoServ().VideoInfoService(ctx, vid)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	resp.Videoinfo = result
	resp.Base = srverror.WrapWithSuccess("查询视频信息成功")
	c.JSON(consts.StatusOK, resp)
}
