// Code generated by hertz generator.

package course

import (
	"context"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/model/base"
	course "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/model/course"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/model/srverror"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/service"
	"github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"net/http"
	"strconv"
)

// CourseInfo .
// @router /course/info [POST]
func CourseInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.CourseInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(course.CourseInfoResp)
	resp.Base = new(base.BaseResponse)
	_, _, err = utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	cid, err := strconv.ParseInt(req.Cid, 10, 64)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		hlog.Error("课程域id数据格式转换失败失败：", err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	result, err := service.CourseServ().CourseInfoWithCid(ctx, cid)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Courseinfo = result

	members, err := service.CourseServ().CourseMembersInfoWithCid(ctx, cid)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Membersinfo = members
	resp.Base = srverror.WrapWithSuccess("查询课程域信息成功")
	c.JSON(consts.StatusOK, resp)
}

// CourseVideosInfo .
// @router /course/videos [POST]
func CourseVideosInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.CourseVideosInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(course.CourseVideosInfoResp)
	resp.Base = new(base.BaseResponse)
	_, _, err = utils.AuthCheck(c)
	if err != nil {
		resp.Base.Code = http.StatusUnauthorized
		resp.Base.Msg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	cid, err := strconv.ParseInt(req.Cid, 10, 64)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		hlog.Error("课程域id数据格式转换失败：", err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	result, err := service.CourseServ().CourseVideosInfoWithCid(ctx, cid)
	if err != nil {
		resp.Base = srverror.WrapWithError(http.StatusBadRequest, err)
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Videosinfo = result
	resp.Base = srverror.WrapWithSuccess("查询课程域视频列表信息成功")
	c.JSON(consts.StatusOK, resp)
}
