// Code generated by hertz generator.

package admin

import (
	middleware "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/middelware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyToken(),
	}
}

func _createcourseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetargetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecourseinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _courseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserfromcourseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _importstudentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _selectcourseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _selectuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _selectvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _enquirytcourseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _enquiryuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _enquiryvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}
