// Code generated by hertz generator.

package class

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryclassMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _classMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addclassMw() []app.HandlerFunc {
	// your code...
	return nil
}
