// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	course "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/course"
	user "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/user"
	video "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/video"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	video.Register(r)

	course.Register(r)

	user.Register(r)

}
