// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	admin "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/admin"
	comment "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/comment"
	course "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/course"
	notification "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/notification"
	user "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/user"
	video "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/video"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	notification.Register(r)

	comment.Register(r)

	admin.Register(r)

	video.Register(r)

	course.Register(r)

	user.Register(r)

}
