// Code generated by hertz generator. DO NOT EDIT.

package router

import (
<<<<<<< Updated upstream
=======
	admin "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/admin"
	course "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/course"
>>>>>>> Stashed changes
	user "github.com/RookiePeckEachOtherCode/KnowledgeStream/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
<<<<<<< Updated upstream
=======
	admin.Register(r)

	video.Register(r)

	course.Register(r)

>>>>>>> Stashed changes
	user.Register(r)

}
