// Code generated by hertz generator.

package statistics

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _teacherstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videostatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoplaysstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}
